sudo: false

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  - cd $TRAVIS_BUILD_DIR/..
  - wget https://dl.google.com/android/repository/android-ndk-r14-beta1-linux-x86_64.zip -O ndk.zip
  - chmod a+x ndk.zip
  - unzip ndk.zip > /dev/null
  - rm ndk.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r14-beta1
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - echo $PATH

before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone -b dmach-build https://github.com/simonnorberg/pd-for-android.git pd-for-android
  - cd pd-for-android
  - git submodule update --init --recursive
  - ./gradlew PdCore:assembleRelease

script:
  - cd $TRAVIS_BUILD_DIR
  - ./gradlew assemble

notifications:
  email: false
